vagrant: checksum update
Update SHASUM for vagrant cask

This is required, as users are currently seeing SHASUM mismatches when trying to install the vagrant cask via the official cask. The apple artifacts were resigned and notarized, and shasums were updated, as part of hashicorp maintenance this morning (more info in https://status.hashicorp.com/incidents/xbbwr755y78b):

```
elle@elle-LD64KN442W Downloads % brew reinstall --cask vagrant
==> Downloading https://releases.hashicorp.com/vagrant/2.3.4/vagrant_2.3.4_darwin_amd64.dmg
Already downloaded: /Users/elle/Library/Caches/Homebrew/downloads/42e309b6a372ee35af42017a677ef41507b8d183dcbd7b4f1af172c9070e4dee--vagrant_2.3.4_darwin_amd64.dmg
Error: SHA256 mismatch
Expected: 8fd27ac9b6faa7a42fcf4b74b25150301f957e9251a1f193d1195b31464fe054
  Actual: 0015f971c20cce4cd3c97ed758f1e0b528bffe0dc02f0ab55da4b216cb5748b8
    File: /Users/elle/Library/Caches/Homebrew/downloads/42e309b6a372ee35af42017a677ef41507b8d183dcbd7b4f1af172c9070e4dee--vagrant_2.3.4_darwin_amd64.dmg
To retry an incomplete download, remove the file above.
```

We've already updated the offical hashicorp homebrew tap at https://github.com/hashicorp/homebrew-tap/commit/92966c57f49e6e9b771b3b3ebc82cc7eb1fcc652.

Closes #139870.

Signed-off-by: Sean Molenaar <1484494+SMillerDev@users.noreply.github.com>
Signed-off-by: BrewTestBot <1589480+BrewTestBot@users.noreply.github.com>