fix dependency name conflict
Current dependency name will be conficted with the formula name of
homebrew/version/ruby20.rb, in result it will cause following error:

```
$ brew readall
Error: problem in /usr/local/Library/Formula/ruby20.rb
wrong number of arguments (3 for 0..1)
```

Fixes https://github.com/Homebrew/homebrew/issues/38638